"""empty message

Revision ID: 181514473a74
Revises: 2c2394fc92ba
Create Date: 2025-05-08 12:21:24.156543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181514473a74'
down_revision = '2c2394fc92ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_post_id_fkey', 'medias', ['post_id'], ['id'])

    # ### end Alembic commands ###
