"""empty message

Revision ID: c95ac7fb1fc6
Revises: a677d0465cfd
Create Date: 2025-05-08 11:50:08.563590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95ac7fb1fc6'
down_revision = 'a677d0465cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followwesinout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('followwesinout_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_from_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followwesinout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followwesinout_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_from_id')
        batch_op.drop_column('user_to_id')

    # ### end Alembic commands ###
